modLoader="javafml"
loaderVersion="[38,)"
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/Rexbas/Bouncing-Balls-API/issues"
logoFile="logo.png"
[[mods]]
modId="bouncingballs_api"
version="${file.jarVersion}"
displayName="Bouncing Balls API"
updateJSONURL="https://forge.curseupdate.com/651871/bouncingballs_api"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bouncing-balls-api"
authors="Rexbas"
description='''
Bouncing Balls API.
'''